### ISSUE TITLE
Hi Wendy! 

### ISSUE THREAD

**Issue by ceciliarong** [WendyMunmunWang/timeseries443#7]
Are u coming to the team meeting today at 2pm? We are in room X151.

**Comment by wenwangcode** [comment]
Hey, no I'm not coming because I have a cold and i am not feeling too well :( . I sent you guys a message on Slack this morning. Sorry that I am not able to make it. I added an additional table in the google docs to compare the three models.

could you guys focus on doing prediction and then compare results for the models for the meeting?
1. maybe predict March 2nd, 3rd, 4th and 7th - 11th using  all of the three models
2. and list out all the comparisons as well as the real result

Please let me know what else i can do. Thanks!

**Comment by ceciliarong** [comment]
No problem. Take care! 

We are discussing a new model right now, and will post any update when finish. Take care urself!

**Comment by wenwangcode** [comment]
Hi Cecilia, I was wondering what's the updates for the meeting? I checked the google docs but nothing is updated

**Comment by ceciliarong** [comment]
Hi Wendy, how are you? We tried to explore several different models and plots yesterday. You may noticed that Geoff uploaded a new data set called "SP500janmar.csv" earlier, the new data set might be better in a sense of catching the trend in the rapidly changing financial market and thus might do a better job in predicting. 

We temporately divideded the remaining tasks to write the project as follows: Geoff will be responsible for a new model, Clay will be responsible for the introduction, or might be some cross-validating comparision, and I will be responsible for the second ratio model using the new data set. Could you do the original first model using the new data set?

**Comment by lion-hearted-achilles** [comment]
Just to second this, we looked carefully at the models which use decades of data. None of them was an adequate fit after a few lags--usually around 7. This is probably because financial markets are too variable to remain consistent over that span of time, and so it's close to impossible to model such data using time series methods (particularly for us in an introductory class!).

Bruce mentioned online that he wanted us to restrict attention to the past few months because data will seem more stationary when you restrict it to a short span of time.

**Comment by lion-hearted-achilles** [comment]
Also, like you mentioned online, so long as we are logical and use the tools of this course correctly, everything should be fine regarding the marks.
