### ISSUE TITLE
Transformation of second model back to X(t) scale

### ISSUE THREAD

**Issue by lion-hearted-achilles** [WendyMunmunWang/timeseries443#9]
Hi Cecilia!

Could you explain the equation you used to transform the lagratio predictions from W(t) back to the X(t) scale? It's a very interesting approach! I don't understand these numbers in particular:

2035.94 -- looks like X(N) for some number N
100.01869 -- looks like W(M) for some number M

**Comment by ceciliarong** [comment]
Hi Geoff! This is what I think:

There are 59 data points in X(t), and 58 data points in W(t). By the way a forward ratio defined, it seems the last point of W(t) is log (X(N) / X(N-1)) + 100 , for sample siza N=59. So the first prediction point W( L =1) = X(N+1) / X(N)  .   

The last point of X(t) = 2035.94, and first prediction of W(t) = 100.01869. Since W( L=1) = log (X(N+1) / X(N) )   + 100, it follows that X(N+1) = ( W(L=1) - 100) \* X(N).

But there seems that I made a typo in the R code. I just made a correction.  I think the correct one should be

pred.x.1 <- (exp(100.01869 - 100)) \* 2035.94 
pred.x.2 <- exp(pred.w[1] - 100) \* pred.x.1
pred.x.3 <- exp(pred.w[2] - 100) \* pred.x.2
pred.x.4 <- exp(pred.w[3] - 100) \* pred.x.3
pred.x.5 <- exp(pred.w[4] - 100) \* pred.x.4

instead of the original:

pred.x.1 <- (exp(100.01869 - 100)) \* 2035.94 
pred.x.2 <- exp(pred.w[1] - 100) \* pred.x.1
pred.x.3 <- exp(pred.w[2] - 100) \* pred.x.1
pred.x.4 <- exp(pred.w[3] - 100) \* pred.x.1
pred.x.5 <- exp(pred.w[4] - 100) \* pred.x.1

**Comment by lion-hearted-achilles** [comment]
Thanks Cecilia! I shifted things around a little so we didn't rely on that forecast (although it's a cool approach) since I just saw your response.
